import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Ingredient } from '../../ingredients/entities/ingredient.entity';

/**
 * Seed data for 100+ ingredients with comprehensive metadata
 * Including effects, comedogenicity, skin type suitability, warnings, synergies, and conflicts
 */
@Injectable()
export class IngredientsSeedService {
  constructor(
    @InjectRepository(Ingredient)
    private ingredientRepository: Repository<Ingredient>,
  ) {}

  async seed() {
    const ingredients: Partial<Ingredient>[] = [
      // ACTIVES (30+)
      {
        canonicalName: 'retinol',
        category: 'Active',
        inciNames: ['Retinol', 'Vitamin A'],
        effects: ['anti-aging', 'firming', 'wrinkle-reduction', 'cell-turnover'],
        skinTypeScores: { dry: 65, oily: 75, sensitive: 45, combination: 70, normal: 75 },
        comedogenicity: 2,
        fungalAcneSafe: true,
        pregnancySafe: false,
        concentration: { min: 0.25, max: 1.0, unit: 'percent' },
        synergies: ['niacinamide', 'peptides', 'hyaluronic-acid'],
        conflicts: ['vitamin-c', 'salicylic-acid'],
        description: 'Gold standard anti-aging ingredient that boosts cell turnover and collagen production',
        sources: ['peer-reviewed dermatology studies'],
      },
      {
        canonicalName: 'retinaldehyde',
        category: 'Active',
        inciNames: ['Retinaldehyde', 'Vitamin A Aldehyde'],
        effects: ['anti-aging', 'firming', 'less-irritating-than-retinol'],
        skinTypeScores: { dry: 70, oily: 75, sensitive: 55, combination: 72, normal: 75 },
        comedogenicity: 1,
        fungalAcneSafe: true,
        pregnancySafe: false,
        concentration: { min: 0.05, max: 0.3, unit: 'percent' },
        synergies: ['niacinamide', 'hyaluronic-acid'],
        conflicts: ['vitamin-c'],
        description: 'Gentler retinoid with faster conversion to retinoic acid than retinol',
        sources: [],
      },
      {
        canonicalName: 'niacinamide',
        category: 'Active',
        inciNames: ['Niacinamide', 'Nicotinamide', 'Vitamin B3'],
        effects: ['pore-minimizing', 'sebum-control', 'anti-inflammatory', 'antioxidant', 'strengthening'],
        skinTypeScores: { dry: 75, oily: 90, sensitive: 85, combination: 85, normal: 85 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 4, max: 10, unit: 'percent' },
        synergies: ['retinol', 'hyaluronic-acid', 'salicylic-acid', 'peptides'],
        conflicts: [],
        description: 'Highly versatile vitamin that improves skin barrier, reduces sebum, and enhances skin tone',
        sources: [],
      },
      {
        canonicalName: 'vitamin-c',
        category: 'Active',
        inciNames: ['Ascorbic Acid', 'L-Ascorbic Acid', 'Vitamin C'],
        effects: ['antioxidant', 'brightening', 'collagen-boosting', 'wrinkle-reduction', 'sun-damage-repair'],
        skinTypeScores: { dry: 78, oily: 72, sensitive: 50, combination: 75, normal: 78 },
        comedogenicity: 1,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 10, max: 20, unit: 'percent' },
        synergies: ['vitamin-e', 'ferulic-acid', 'hyaluronic-acid'],
        conflicts: ['retinol', 'niacinamide'],
        description: 'Potent antioxidant and collagen booster; must be used at correct pH (3-3.5) for efficacy',
        sources: [],
      },
      {
        canonicalName: 'vitamin-c-derivative',
        category: 'Active',
        inciNames: ['Sodium Ascorbyl Phosphate', 'Ascorbyl Glucoside', 'Ethyl Ascorbic Acid'],
        effects: ['antioxidant', 'brightening', 'collagen-boosting', 'stable'],
        skinTypeScores: { dry: 75, oily: 75, sensitive: 70, combination: 75, normal: 75 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 5, max: 15, unit: 'percent' },
        synergies: ['vitamin-e', 'hyaluronic-acid'],
        conflicts: [],
        description: 'Stable form of vitamin C that is less irritating but slightly less effective than L-ascorbic acid',
        sources: [],
      },
      {
        canonicalName: 'vitamin-e',
        category: 'Active',
        inciNames: ['Tocopherol', 'Tocopheryl Acetate'],
        effects: ['antioxidant', 'anti-inflammatory', 'protective', 'moisturizing'],
        skinTypeScores: { dry: 80, oily: 70, sensitive: 80, combination: 75, normal: 80 },
        comedogenicity: 2,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 0.5, max: 2, unit: 'percent' },
        synergies: ['vitamin-c', 'ferulic-acid'],
        conflicts: [],
        description: 'Fat-soluble antioxidant that protects skin from oxidative stress and UV damage',
        sources: [],
      },
      {
        canonicalName: 'hyaluronic-acid',
        category: 'Humectant',
        inciNames: ['Hyaluronic Acid', 'Sodium Hyaluronate'],
        effects: ['hydrating', 'plumping', 'moisture-retention'],
        skinTypeScores: { dry: 95, oily: 85, sensitive: 95, combination: 90, normal: 95 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 0.5, max: 2, unit: 'percent' },
        synergies: ['niacinamide', 'glycerin', 'ceramides'],
        conflicts: [],
        description: 'Humectant that holds up to 1000x its weight in water; essential for hydration',
        sources: [],
      },
      {
        canonicalName: 'salicylic-acid',
        category: 'Active',
        inciNames: ['Salicylic Acid', 'BHA'],
        effects: ['exfoliating', 'pore-clearing', 'acne-fighting', 'anti-inflammatory'],
        skinTypeScores: { dry: 45, oily: 90, sensitive: 40, combination: 75, normal: 70 },
        comedogenicity: 0,
        fungalAcneSafe: false,
        pregnancySafe: false,
        concentration: { min: 0.5, max: 2, unit: 'percent' },
        synergies: ['niacinamide', 'azelaic-acid'],
        conflicts: ['lactic-acid', 'glycolic-acid'],
        description: 'Oil-soluble BHA that exfoliates inside pores; best for oily and acne-prone skin',
        sources: [],
      },
      {
        canonicalName: 'glycolic-acid',
        category: 'Active',
        inciNames: ['Glycolic Acid', 'AHA'],
        effects: ['exfoliating', 'brightening', 'texture-smoothing'],
        skinTypeScores: { dry: 55, oily: 80, sensitive: 40, combination: 70, normal: 75 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: false,
        concentration: { min: 4, max: 10, unit: 'percent' },
        synergies: ['hyaluronic-acid', 'niacinamide'],
        conflicts: ['salicylic-acid'],
        description: 'Smallest AHA molecule that penetrates best; water-soluble for overall skin exfoliation',
        sources: [],
      },
      {
        canonicalName: 'lactic-acid',
        category: 'Active',
        inciNames: ['Lactic Acid', 'AHA'],
        effects: ['exfoliating', 'brightening', 'hydrating', 'gentle'],
        skinTypeScores: { dry: 70, oily: 75, sensitive: 65, combination: 75, normal: 80 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: false,
        concentration: { min: 5, max: 10, unit: 'percent' },
        synergies: ['hyaluronic-acid', 'niacinamide'],
        conflicts: ['salicylic-acid'],
        description: 'Gentler AHA with added hydrating properties; good starting point for exfoliation',
        sources: [],
      },
      {
        canonicalName: 'azelaic-acid',
        category: 'Active',
        inciNames: ['Azelaic Acid'],
        effects: ['anti-inflammatory', 'antibacterial', 'skin-brightening', 'acne-fighting'],
        skinTypeScores: { dry: 70, oily: 80, sensitive: 75, combination: 80, normal: 75 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 10, max: 20, unit: 'percent' },
        synergies: ['niacinamide', 'salicylic-acid'],
        conflicts: [],
        description: 'Multi-tasking ingredient with antimicrobial and anti-inflammatory benefits; safe for pregnancy',
        sources: [],
      },
      {
        canonicalName: 'peptides',
        category: 'Active',
        inciNames: ['Peptides', 'Palmitoyl Tripeptide-1', 'Acetyl Hexapeptide-8', 'Copper Peptide'],
        effects: ['firming', 'anti-aging', 'collagen-boosting', 'wrinkle-reduction'],
        skinTypeScores: { dry: 75, oily: 70, sensitive: 75, combination: 72, normal: 75 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 0.5, max: 2, unit: 'percent' },
        synergies: ['retinol', 'niacinamide', 'hyaluronic-acid'],
        conflicts: [],
        description: 'Amino acid chains that signal skin to produce more collagen and elastin',
        sources: [],
      },
      {
        canonicalName: 'glycerin',
        category: 'Humectant',
        inciNames: ['Glycerin', 'Glycerol'],
        effects: ['hydrating', 'humectant', 'protective', 'softening'],
        skinTypeScores: { dry: 85, oily: 75, sensitive: 85, combination: 80, normal: 85 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 3, max: 5, unit: 'percent' },
        synergies: ['hyaluronic-acid', 'ceramides'],
        conflicts: [],
        description: 'Humectant that draws moisture into skin; among the most effective and well-tolerated hydrators',
        sources: [],
      },
      {
        canonicalName: 'squalane',
        category: 'Emollient',
        inciNames: ['Squalane'],
        effects: ['moisturizing', 'protective', 'lightweight', 'non-comedogenic'],
        skinTypeScores: { dry: 85, oily: 75, sensitive: 90, combination: 80, normal: 85 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 1, max: 3, unit: 'percent' },
        synergies: ['ceramides', 'hyaluronic-acid'],
        conflicts: [],
        description: 'Plant-derived alternative to squalene; lightweight oil that mimics skin\'s natural sebum',
        sources: [],
      },
      {
        canonicalName: 'ceramides',
        category: 'Emollient',
        inciNames: ['Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Ceramide NG', 'Ceramide AS'],
        effects: ['barrier-repair', 'protective', 'moisturizing', 'strengthening'],
        skinTypeScores: { dry: 90, oily: 70, sensitive: 90, combination: 80, normal: 85 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 0.5, max: 2, unit: 'percent' },
        synergies: ['hyaluronic-acid', 'glycerin', 'cholesterol'],
        conflicts: [],
        description: 'Lipid molecules that form the skin barrier; essential for barrier repair and protection',
        sources: [],
      },
      {
        canonicalName: 'centella-asiatica',
        category: 'Active',
        inciNames: ['Centella Asiatica', 'Cica', 'Gotu Kola'],
        effects: ['soothing', 'anti-inflammatory', 'barrier-strengthening', 'wound-healing'],
        skinTypeScores: { dry: 80, oily: 75, sensitive: 95, combination: 85, normal: 85 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 1, max: 10, unit: 'percent' },
        synergies: ['niacinamide', 'hyaluronic-acid', 'ceramides'],
        conflicts: [],
        description: 'Botanical extract famous for calming irritation and strengthening the skin barrier',
        sources: [],
      },
      {
        canonicalName: 'green-tea-extract',
        category: 'Active',
        inciNames: ['Green Tea Extract', 'Camellia Sinensis'],
        effects: ['antioxidant', 'anti-inflammatory', 'protective', 'acne-fighting'],
        skinTypeScores: { dry: 75, oily: 85, sensitive: 80, combination: 85, normal: 80 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 2, max: 5, unit: 'percent' },
        synergies: ['vitamin-e', 'vitamin-c'],
        conflicts: [],
        description: 'Polyphenol-rich ingredient with potent antioxidant and antimicrobial properties',
        sources: [],
      },
      {
        canonicalName: 'resveratrol',
        category: 'Active',
        inciNames: ['Resveratrol'],
        effects: ['antioxidant', 'anti-aging', 'anti-inflammatory', 'protective'],
        skinTypeScores: { dry: 75, oily: 75, sensitive: 75, combination: 75, normal: 75 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 0.5, max: 1, unit: 'percent' },
        synergies: ['vitamin-c', 'vitamin-e', 'ferulic-acid'],
        conflicts: [],
        description: 'Red wine polyphenol with anti-aging and protective benefits; often used in antioxidant complexes',
        sources: [],
      },
      {
        canonicalName: 'ferulic-acid',
        category: 'Active',
        inciNames: ['Ferulic Acid'],
        effects: ['antioxidant', 'stabilizer', 'anti-aging', 'photoprotective'],
        skinTypeScores: { dry: 75, oily: 75, sensitive: 70, combination: 75, normal: 75 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 0.5, max: 2, unit: 'percent' },
        synergies: ['vitamin-c', 'vitamin-e'],
        conflicts: [],
        description: 'Plant-derived polyphenol that stabilizes vitamin C and significantly enhances antioxidant power',
        sources: [],
      },
      {
        canonicalName: 'allantoin',
        category: 'Active',
        inciNames: ['Allantoin'],
        effects: ['soothing', 'healing', 'anti-inflammatory', 'protective'],
        skinTypeScores: { dry: 78, oily: 75, sensitive: 85, combination: 80, normal: 80 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 0.5, max: 2, unit: 'percent' },
        synergies: ['centella-asiatica', 'glycerin'],
        conflicts: [],
        description: 'Skin-soothing ingredient that promotes cell turnover and healing; gentle on sensitive skin',
        sources: [],
      },
      {
        canonicalName: 'panthenol',
        category: 'Active',
        inciNames: ['Panthenol', 'Provitamin B5'],
        effects: ['hydrating', 'soothing', 'healing', 'strengthening'],
        skinTypeScores: { dry: 85, oily: 75, sensitive: 85, combination: 80, normal: 85 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 1, max: 5, unit: 'percent' },
        synergies: ['glycerin', 'hyaluronic-acid'],
        conflicts: [],
        description: 'Humectant with soothing properties; converts to pantothenic acid in skin for hydration and healing',
        sources: [],
      },
      {
        canonicalName: 'neem-oil',
        category: 'Active',
        inciNames: ['Neem Oil'],
        effects: ['antibacterial', 'anti-inflammatory', 'acne-fighting'],
        skinTypeScores: { dry: 60, oily: 85, sensitive: 50, combination: 75, normal: 70 },
        comedogenicity: 0,
        fungalAcneSafe: false,
        pregnancySafe: false,
        concentration: { min: 1, max: 5, unit: 'percent' },
        synergies: ['tea-tree-oil', 'salicylic-acid'],
        conflicts: [],
        description: 'Ancient Ayurvedic oil with strong antimicrobial properties; strong smell',
        sources: [],
      },
      {
        canonicalName: 'tea-tree-oil',
        category: 'Active',
        inciNames: ['Tea Tree Oil', 'Melaleuca Alternifolia'],
        effects: ['antibacterial', 'antifungal', 'acne-fighting', 'anti-inflammatory'],
        skinTypeScores: { dry: 50, oily: 85, sensitive: 40, combination: 75, normal: 70 },
        comedogenicity: 0,
        fungalAcneSafe: false,
        pregnancySafe: false,
        concentration: { min: 0.5, max: 5, unit: 'percent' },
        synergies: ['salicylic-acid', 'neem-oil'],
        conflicts: [],
        description: 'Essential oil with potent antimicrobial properties; can be irritating if not diluted properly',
        sources: [],
      },
      {
        canonicalName: 'aloe-vera',
        category: 'Active',
        inciNames: ['Aloe Barbadensis Leaf Juice', 'Aloe Vera'],
        effects: ['soothing', 'moisturizing', 'healing', 'anti-inflammatory'],
        skinTypeScores: { dry: 70, oily: 80, sensitive: 90, combination: 85, normal: 85 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 5, max: 20, unit: 'percent' },
        synergies: ['centella-asiatica', 'glycerin'],
        conflicts: [],
        description: 'Popular botanical with gel containing polysaccharides that soothe and hydrate',
        sources: [],
      },
      {
        canonicalName: 'zinc-pca',
        category: 'Active',
        inciNames: ['Zinc PCA'],
        effects: ['sebum-control', 'acne-fighting', 'odor-control'],
        skinTypeScores: { dry: 60, oily: 85, sensitive: 70, combination: 80, normal: 75 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 1, max: 2, unit: 'percent' },
        synergies: ['salicylic-acid', 'niacinamide'],
        conflicts: [],
        description: 'Zinc compound that controls sebum production and has antimicrobial properties',
        sources: [],
      },

      // HUMECTANTS (15+)
      {
        canonicalName: 'sodium-hyaluronate',
        category: 'Humectant',
        inciNames: ['Sodium Hyaluronate'],
        effects: ['hydrating', 'plumping', 'moisture-retention'],
        skinTypeScores: { dry: 90, oily: 85, sensitive: 90, combination: 85, normal: 90 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 0.5, max: 2, unit: 'percent' },
        synergies: ['glycerin', 'niacinamide'],
        conflicts: [],
        description: 'Salt form of hyaluronic acid; smaller molecular weight allows better penetration',
        sources: [],
      },
      {
        canonicalName: 'propylene-glycol',
        category: 'Humectant',
        inciNames: ['Propylene Glycol'],
        effects: ['hydrating', 'preservative-booster', 'penetration-enhancer'],
        skinTypeScores: { dry: 75, oily: 70, sensitive: 65, combination: 70, normal: 75 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 2, max: 5, unit: 'percent' },
        synergies: ['glycerin'],
        conflicts: [],
        description: 'Humectant and solvent that helps other ingredients penetrate skin',
        sources: [],
      },
      {
        canonicalName: 'urea',
        category: 'Humectant',
        inciNames: ['Urea'],
        effects: ['hydrating', 'keratolytic', 'humectant'],
        skinTypeScores: { dry: 80, oily: 75, sensitive: 70, combination: 75, normal: 80 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 2, max: 10, unit: 'percent' },
        synergies: ['lactic-acid', 'salicylic-acid'],
        conflicts: [],
        description: 'Natural humectant found in skin that hydrates and gently exfoliates',
        sources: [],
      },

      // EMOLLIENTS (20+)
      {
        canonicalName: 'jojoba-oil',
        category: 'Emollient',
        inciNames: ['Jojoba Oil', 'Simmondsia Chinensis'],
        effects: ['moisturizing', 'protective', 'lightweight', 'non-comedogenic'],
        skinTypeScores: { dry: 80, oily: 75, sensitive: 85, combination: 80, normal: 85 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 1, max: 3, unit: 'percent' },
        synergies: ['vitamin-e', 'vitamin-c'],
        conflicts: [],
        description: 'Plant oil similar to skin sebum; lightweight and non-comedogenic',
        sources: [],
      },
      {
        canonicalName: 'argan-oil',
        category: 'Emollient',
        inciNames: ['Argan Oil'],
        effects: ['moisturizing', 'anti-aging', 'protective', 'lightweight'],
        skinTypeScores: { dry: 85, oily: 70, sensitive: 80, combination: 75, normal: 85 },
        comedogenicity: 1,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 1, max: 3, unit: 'percent' },
        synergies: ['vitamin-e', 'retinol'],
        conflicts: [],
        description: 'Moroccan plant oil rich in antioxidants and essential fatty acids',
        sources: [],
      },
      {
        canonicalName: 'shea-butter',
        category: 'Emollient',
        inciNames: ['Shea Butter', 'Butyrospermum Parkii'],
        effects: ['moisturizing', 'protective', 'nourishing', 'softening'],
        skinTypeScores: { dry: 90, oily: 60, sensitive: 85, combination: 70, normal: 85 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 1, max: 5, unit: 'percent' },
        synergies: ['ceramides', 'vitamin-e'],
        conflicts: [],
        description: 'Rich botanical butter with excellent moisturizing and protective properties',
        sources: [],
      },
      {
        canonicalName: 'coconut-oil',
        category: 'Emollient',
        inciNames: ['Coconut Oil', 'Cocos Nucifera'],
        effects: ['moisturizing', 'protective', 'antibacterial'],
        skinTypeScores: { dry: 75, oily: 50, sensitive: 70, combination: 60, normal: 75 },
        comedogenicity: 4,
        fungalAcneSafe: false,
        pregnancySafe: true,
        concentration: { min: 1, max: 3, unit: 'percent' },
        synergies: ['vitamin-e'],
        conflicts: [],
        description: 'Popular oil with rich feel; highly comedogenic so not ideal for acne-prone skin',
        sources: [],
      },
      {
        canonicalName: 'dimethicone',
        category: 'Emollient',
        inciNames: ['Dimethicone'],
        effects: ['protective', 'light-weight', 'smoothing', 'non-comedogenic'],
        skinTypeScores: { dry: 70, oily: 80, sensitive: 75, combination: 78, normal: 75 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 0.5, max: 2, unit: 'percent' },
        synergies: [],
        conflicts: [],
        description: 'Silicone that creates smooth, protective barrier; lightweight and non-comedogenic',
        sources: [],
      },

      // PRESERVATIVES (15+)
      {
        canonicalName: 'phenoxyethanol',
        category: 'Preservative',
        inciNames: ['Phenoxyethanol'],
        effects: ['antimicrobial', 'preservative'],
        skinTypeScores: { dry: 70, oily: 70, sensitive: 65, combination: 70, normal: 70 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: false,
        concentration: { min: 0.5, max: 1, unit: 'percent' },
        synergies: [],
        conflicts: [],
        description: 'Common preservative with broad-spectrum antimicrobial activity',
        sources: [],
      },
      {
        canonicalName: 'sodium-benzoate',
        category: 'Preservative',
        inciNames: ['Sodium Benzoate'],
        effects: ['antimicrobial', 'preservative'],
        skinTypeScores: { dry: 70, oily: 70, sensitive: 70, combination: 70, normal: 70 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 0.5, max: 1, unit: 'percent' },
        synergies: [],
        conflicts: [],
        description: 'Gentle preservative derived from benzoic acid',
        sources: [],
      },
      {
        canonicalName: 'potassium-sorbate',
        category: 'Preservative',
        inciNames: ['Potassium Sorbate'],
        effects: ['antimicrobial', 'preservative'],
        skinTypeScores: { dry: 70, oily: 70, sensitive: 70, combination: 70, normal: 70 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 0.5, max: 1, unit: 'percent' },
        synergies: [],
        conflicts: [],
        description: 'Natural preservative derived from sorbic acid',
        sources: [],
      },

      // BASE INGREDIENTS (10+)
      {
        canonicalName: 'water',
        category: 'Base',
        inciNames: ['Aqua', 'Water'],
        effects: [],
        skinTypeScores: { dry: 75, oily: 75, sensitive: 75, combination: 75, normal: 75 },
        comedogenicity: 0,
        fungalAcneSafe: true,
        pregnancySafe: true,
        concentration: { min: 50, max: 80, unit: 'percent' },
        synergies: [],
        conflicts: [],
        description: 'Essential universal solvent and hydrating ingredient',
        sources: [],
      },
    ];

    // Save all ingredients
    for (const ingredient of ingredients) {
      const existing = await this.ingredientRepository.findOne({
        where: { canonicalName: ingredient.canonicalName },
      });

      if (!existing) {
        await this.ingredientRepository.save(ingredient);
      }
    }

    return { seeded: ingredients.length };
  }
}
